In [2]:
'''
Matrix Arithmatic: primararily for NN training 
'''

import numpy as np

In [ ]:
# column vector
a = np.array([1,2,3])       # 1D list
a_col = np.reshape(a,(3,1)) # actual col vector
a_col


array([[1],
       [2],
       [3]])

In [16]:
np.shape(a_col)

(3, 1)

In [6]:
### 3x3 matrix
b = np.array([
    [10,20,30],
    [10,20,30],
    [10,20,30]
    ])
np.shape(b)

(3, 3)

In [ ]:
prod_col = a_col*b
prod_col

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [17]:
mat_prod = np.dot(b, a_col)
mat_prod

array([[140],
       [140],
       [140]])

In [18]:
np.shape(mat_prod)

(3, 1)

In [9]:
### Row vector for a
row_a = a.reshape(1,3) # 1 row with 3 entries(3 columns)
np.shape(row_a)

(1, 3)

In [19]:
### row mult 

prod_row = row_a*b
prod_row

array([[10, 40, 90],
       [10, 40, 90],
       [10, 40, 90]])

In [20]:
res = np.dot(row_a, b)
res

array([[ 60, 120, 180]])

In [21]:
np.shape(res)

(1, 3)

In [ ]:
#### Dot product work with some shape incoherency due to them being more vector concentrated.
#### Matrix mult requires shape checking and arrangement

